# Site settings
title: Duana Severiano
header-img: img/Mies.jpg
email: dseveria@hawk.iit.edu
copyright_name: Duana
description: "Duana's awesome Digital Fabrication Research"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://dseveria.github.io/"
twitter_username: duseveri
github_username:  dseveria
facebook_username:  duana.severiano
email_username:  dseveria@hawk.iit.edu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
